### ISSUE TITLE
Fix issues with latest LWJGL snapshot

### ISSUE THREAD

**Issue by lwjglgamedev** [lwjglgamedev/vulkanbook#26]
Fix compilation issues and runtime errors

**Comment by tlf30** [comment]
Just got hit with this commit on the LWJGL snapshot: https://github.com/LWJGL/lwjgl3/commit/0c4a2bcdf53fd73f569832c928074ca1074d5fdd

I thought you might be interested. Basically all vulkan objects the calloc/mallocStack is now calloc/malloc. Bulk find and replace should work, it worked for me on my projects.

**Comment by lwjglgamedev** [comment]
Hi,

I was about to submit a fix for that. I think I've covered all the cases. If you still find something missing, please let me know. I've also added an option in the root `pom.xml`  to warn about deprecations.

**Comment by tlf30** [comment]
Something to keep an eye on, the implementation may not be set in stone yet: https://github.com/LWJGL/lwjgl3/issues/537

**Comment by lwjglgamedev** [comment]
Yes. I'm following that. My current understanding is that old methods will still available. So the questions is if we should use the new ones or maintain the old ones (which are similar to Vulkan C code and samples).

LWJGL 3.0.0 final release seems to be inminent.

**Comment by tlf30** [comment]
I think for clarity, it would be best to continue  to use the C style function. 

I hope 3.3.0 is around the corner!

**Comment by tlf30** [comment]
Well, 3.3.0 is released!

**Comment by lwjglgamedev** [comment]
Correct. The code is already updated to use 3.3.0 release.
