### ISSUE TITLE
Add section on loss of device troubleshooting

### ISSUE THREAD

**Issue by tlf30** [lwjglgamedev/vulkanbook#30]
It would be great to get a section on how to troubleshoot a loss of device error. This is an issue that stumps many people when working with vulkan for the first time. 
Some things that could be included that would be helpful:
* How to use `vkCmdSetCheckpointNV`/`vkGetQueueCheckpointDataNV`/`vkGetQueueCheckpointData2NV` for NVIDIA
* How to use `vkCmdWriteBufferMarkerAMD`/`vkCmdWriteBufferMarker2AMD` for AMD (I'm not even sure how to use these, I have only used the nvidia ones)

Useful link: https://vulkan.lunarg.com/doc/view/1.2.162.1/mac/chunked_spec/chap45.html#_device_loss_debugging

Here is a sample snippet of an implementation I hacked together for the project I am working on. It does not work perfect, especially on older cards (I'm thinking that older drivers have issues with the set checkpoint). Perhaps it may be of use in getting something put together for the book. 

```java
public static String[] getOptionalDebuggingDeviceExtensions() {
        return debugCommandBuffers ?
                new String[] {
                        //NVIDIA: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_device_diagnostic_checkpoints.html
                        VK_NV_DEVICE_DIAGNOSTIC_CHECKPOINTS_EXTENSION_NAME,

                        //AMD: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_AMD_buffer_marker.html
                        //TODO: VK_AMD_BUFFER_MARKER_EXTENSION_NAME,

                        //Optional: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_synchronization2.html
                        VK_KHR_SYNCHRONIZATION_2_EXTENSION_NAME, //Disable for nvidia NSIGHT
                }
                : new String[0];
    }

    public static void debugLostDeviceNV2(Vk12Queue queue) {
        if (!debugCommandBuffers) {
            return;
        }
        if (queue.getDevice().getExtensions().contains(VK_NV_DEVICE_DIAGNOSTIC_CHECKPOINTS_EXTENSION_NAME) && queue.getDevice().getExtensions().contains(VK_KHR_SYNCHRONIZATION_2_EXTENSION_NAME)) {
            try (MemoryStack stack = MemoryStack.stackPush()) {
                IntBuffer count = stack.callocInt(1);
                vkGetQueueCheckpointData2NV(queue.getQueue(), count, null);

                if (count.get(0) > 0) {
                    VkCheckpointData2NV.Buffer checkpointData = VkCheckpointData2NV.calloc(count.get(0));
                    vkGetQueueCheckpointData2NV(queue.getQueue(), count, checkpointData);
                    List<String> checkpoints = new ArrayList<>(count.get(0));
                    for (VkCheckpointData2NV checkpoint : checkpointData.stream().toList()) {
                        checkpoints.add(commandBufferCheckpoints.get((int) checkpoint.pCheckpointMarker() - 1));
                    }
                    LOGGER.severe("Device lost on command buffer checkpoint: \n\t* " + String.join("\n\t* ", checkpoints));
                } else {
                    debugLostDeviceNV(queue);
                }
            }
        } else {
            debugLostDeviceNV(queue);
        }
    }

    public static void debugLostDeviceNV(Vk12Queue queue) {
        if (!debugCommandBuffers) {
            return;
        }
        if (queue.getDevice().getExtensions().contains(VK_NV_DEVICE_DIAGNOSTIC_CHECKPOINTS_EXTENSION_NAME)) {
            try (MemoryStack stack = MemoryStack.stackPush()) {
                IntBuffer count = stack.callocInt(1);
                vkGetQueueCheckpointDataNV(queue.getQueue(), count, null);

                if (count.get(0) > 0) {
                    VkCheckpointDataNV.Buffer checkpointData = VkCheckpointDataNV.calloc(count.get(0));
                    vkGetQueueCheckpointDataNV(queue.getQueue(), count, checkpointData);
                    List<String> checkpoints = new ArrayList<>(count.get(0));
                    for (VkCheckpointDataNV checkpoint : checkpointData.stream().toList()) {
                        checkpoints.add(commandBufferCheckpoints.get((int) checkpoint.pCheckpointMarker() - 1));
                    }
                    LOGGER.severe("Device lost on command buffer checkpoint: " + String.join("\n\t* ", checkpoints));
                } else {
                    LOGGER.warning("No command buffer checkpoints recorded for device lost error.");
                }
            }
        } else {
            debugLostDeviceAMD(queue);
        }
    }

    public static void debugLostDeviceAMD(Vk12Queue queue) {
        if (!debugCommandBuffers) {
            return;
        }
        if (queue.getDevice().getExtensions().contains(VK_AMD_BUFFER_MARKER_EXTENSION_NAME)) {
            //TODO: ???
        } else {
            LOGGER.warning("Cannot debug lost device, missing device extensions.");
        }
    }

    public static void debugCommandBuffer(Vk12CommandBuffer buffer, String commandBufferCheckpoint) {
        if (!debugCommandBuffers) {
            return;
        }
        if (buffer.getCommandPool().getDevice().getExtensions().contains(VK_NV_DEVICE_DIAGNOSTIC_CHECKPOINTS_EXTENSION_NAME)) {
            long checkpointMarker;
            if (!commandBufferCheckpoints.contains(commandBufferCheckpoint)) {
                commandBufferCheckpoints.add(commandBufferCheckpoint);
            }
            checkpointMarker = commandBufferCheckpoints.indexOf(commandBufferCheckpoint);
            vkCmdSetCheckpointNV(buffer.getCommandBuffer(), checkpointMarker + 1);
        } else if (buffer.getCommandPool().getDevice().getExtensions().contains(VK_AMD_BUFFER_MARKER_EXTENSION_NAME)) {
            //TODO: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdWriteBufferMarkerAMD.html
            //TODO: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdWriteBufferMarker2AMD.html
        }
    }
```

Thanks,
Trevor

**Comment by lwjglgamedev** [comment]
Thanks for the suggestion. It could be added in the first chapters when device is created. Let me give a thought about this. Do you know how it can be easely tested? That is, how we can force to lose the device?

In any case, I will need some time. (End of year is allways a complicated period)

**Comment by tlf30** [comment]
Yes, there are several easy ways to cause a loss of device, some actually too easy (one of my big issues with vulkan is the lack of crash info as to why a device was lost). I'll see about getting some samples together that only include what was covered up to creating a device, or at least something that can easily be added to that chapter for demonstration.

**Comment by lwjglgamedev** [comment]
Update, I've just started working on this. I think this could go to an annex. I will let you know whene there is something ussable for you to test it.

**Comment by lwjglgamedev** [comment]
I've just uploaded a draft version. Please have a look and come back with commients (if any)

**Comment by tlf30** [comment]
@lwjglgamedev I just did a quick run though of the code, I have not cloned it yet. I'll do that next. 
Just something I noticed, here: https://github.com/lwjglgamedev/vulkanbook/blob/24caf2cdc99e0023ae0c98f025734a8eecb4cd32/booksamples/appendix-01/src/main/java/org/vulkanb/eng/graph/vk/VulkanUtils.java#L38

This is using `vkGetQueueCheckpointData2NV` to get the number of `VkCheckpointDataNV` structures. I think this should be:
`vkGetQueueCheckpointDataNV`. The `vkGetQueueCheckpointData2NV` requires the `VK_KHR_SYNCHRONIZATION_2`. And on my GPUs, does not seem to work even with that extension. Perhaps I am doing something wrong, I have been testing on a RTX Titan, K2100m, and M220. From what I gather from the documentation, the number of `VkCheckpointDataNV` and `VkCheckpointData2NV` data structures can be different though, so using the correct call for the correct number of structures I think is important. 

But I am curious to know what your findings have been since my implementations have been somewhat flaky on the K2100m and M2200. I have observed on the K2100m the checkpoints being returned out of order, or incomplete list of checkpoints that were passed to the command buffer, and on the M2200 the only checkpoints returned are the last checkpoint before the failure, but duplicated. Yet, my RTX Titan always seems to return the full list of checkpoints up to the error correctly.

Also, my new tried and true way of causing a loss of device error is to have a null pointer in the shader pipeline. An easy one for testing is to build the vertex layout but leave the buffer pointer null. It will crash on binding the pipeline `vkCmdBindPipeline`. 

After breakfast I'll clone it and play with it. Thank you for working on this, I think this will be a valuable addition. 

On a side note: I have been learning how to use NVIDAI Aftermath. So far I have had very limited sucess in getting anything useful out of it. I can get a crash report, but it always just says `DMA pagefault` with no other usable information. It does have a stacktrace into the driver, but without the debugging symbols it just is to garbage pointers. I'm not sure how to get the debugging symbols. Even as a registered NVIDIA developer I did not see them under developer downloads. But the NSight utility does allow for attaching them if someone happened to get them.

**Comment by tlf30** [comment]
For example, to create a loss of device, you can allocate more `VkVertexInputAttributeDescription` then you have buffers.
```
vertexInputAttributes = VkVertexInputAttributeDescription.calloc(bufferCount + 5); //FIXME: Added 5 for testing
```
Interestingly, on my M2200, this situation does not return any checkpoints at all from either `vkGetQueueCheckpointData2NV ` or `vkGetQueueCheckpointDataNV`.

**Comment by lwjglgamedev** [comment]
Hi,

I've just corrected the code to call ``vkGetQueueCheckpointDataNV`. I'm just testing inserting a marker and after that calling to dump the results (not provoked any loss of device yet). What I see is that I goet the check point twice at different stages: `VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT ` and `VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT`. It seems that the check point is marked for each stage it gets executed. To be honest, the specifciation is not clear if this is the normal case or not.

I will try to provoke a device loss and check what I get.

**Comment by tlf30** [comment]
Interesting test, I have never tried to get the checkpoints outside of a loss of device.
