### ISSUE TITLE
Drawing transparent objects with Defferd rendering

### ISSUE THREAD

**Issue by EnterOgawa** [lwjglgamedev/vulkanbook#38]
Thank you very much for your help in this book.
Is there a good way to show the translucent part of [DamagedHelmet.gltf](https://github.com/SaschaWillems/Vulkan-glTF-PBR/blob/master/data/models/DamagedHelmet/glTF-Embedded/DamagedHelmet.gltf) used in Sascha Willems' sample?
I would like to know Defferd + Forward Rendering or other best way.

**Comment by lwjglgamedev** [comment]
Hi,

In the book I apply a quick and irty approach which is discard transparent fragments. If you want yo apply transparencies properly, you should perform a final render pass just for transparent elements.

**Comment by EnterOgawa** [comment]
Thank you.
In this book, the final render path is a light path, so should I just draw the transparent elements with a light path?

**Comment by EnterOgawa** [comment]
> Hi,
> 
> In the book I apply a quick and irty approach which is discard transparent fragments. If you want yo apply transparencies properly, you should perform a final render pass just for transparent elements.

Thank you.
I found the reason why the model was not displayed as expected.
This model included the following

aiTextureType_DIFFUSE
aiTextureType_EMISSIVE
aiTextureType_LIGHTMAP
aiTextureType_BASE_COLOR

I understood that the expected display can be obtained by corresponding to these.

**Comment by lwjglgamedev** [comment]
Hi,

I will try to answer your questions. 

1) Deferred shading always has issues with transparencies. In the book I take a quick approach which discards fragments that are considered transparent (below a certain threshold). If you want to proper apply transparencies, you can:
    a) Use forward rendering. Deferred shading is applicable when you have too many lights, but it may not work for you.
    b) Render transparent elements after light pass has finalized. In this case, you will indeed apply a forward render technique, just for transparent elements, over the buffer which contains the results of the lighting stage. You can apply also light effects in that forward pass.
    c) Explore other alternatives. You can google around. There are tons of articles about this topic.

Regarding the specific model. In the book I also apply a simple approach. If the model has a texture (aiTextureType_DIFFUSE) it will use it for fragment albedo. If it dos not have that, it will use aiTextureType_BASE_COLOR. Currently, emissive and light maps are not used at all.

**Comment by EnterOgawa** [comment]
>    b) Render transparent elements after light pass has finalized. In this case, you will indeed apply a forward render technique, just for transparent elements, over the buffer which contains the results of the lighting stage. You can apply also light effects in that forward pass.

Thanks for the info.
I will try to implement the method b).
