### ISSUE TITLE
About shadow flickering

### ISSUE THREAD

**Issue by EnterOgawa** [lwjglgamedev/vulkanbook#39]
Is there a good way to prevent flickering of distant shadows?

**Comment by lwjglgamedev** [comment]
Hi,
Shadows are a complex topic. You can play with the bias.

**Comment by EnterOgawa** [comment]
> Hi,
> Shadows are a complex topic. You can play with the bias. Another approach is to avoid recalculating the shadow map each time the camera moves, but only when the movement is significant enogh that the cascades should be re-caclulated (for example, you have moved long enough).

I see, it seems like it would be a good idea to recalculate the shadows when there is a big movement.
I'll give it a try.
