### ISSUE TITLE
The shadows falling on the terrain at different heights are out of alignment.

### ISSUE THREAD

**Issue by EnterOgawa** [lwjglgamedev/vulkanbook#40]
It will appear as follows.
![image](https://user-images.githubusercontent.com/113655398/204683115-19c6d8d1-e2ae-46f6-b64b-4c1725d0d5f2.png)

If there is a way to solve this problem, I would appreciate it if you could let me know.

Also, the quality of the shadows seems to be different from the sample here, any idea as to the cause of this?
![image](https://user-images.githubusercontent.com/113655398/204683905-19aa6743-fcaa-4424-9ae3-12b1fe19febc.png)

**Comment by lwjglgamedev** [comment]
I will try to have a look, but you may need to increase the size of the shadow map tetxure and also check the bias.

**Comment by lwjglgamedev** [comment]
If you can, plese share with me your testing repo to have a look. I don't have too much spare time these days and it will help me to diagnose the issue.

**Comment by EnterOgawa** [comment]
> If you can, plese share with me your testing repo to have a look. I don't have too much spare time these days and it will help me to diagnose the issue.
I am very sorry, I found the cause of the misalignment.
I had the illusion that the shadows were out of alignment because the entity was floating against the terrain.
