### ISSUE TITLE
Cascading shadow borders are displayed.

### ISSUE THREAD

**Issue by EnterOgawa** [lwjglgamedev/vulkanbook#42]
What are some possible causes for this?

![image](https://user-images.githubusercontent.com/113655398/205480088-b0839ad9-aed2-42ad-bd7d-769400c0f679.png)

**Comment by lwjglgamedev** [comment]
Missed this (sorry). Please reopen and provide more data (position of the camera mainly) if you still have the issue-

**Comment by EnterOgawa** [comment]
I found the cause of this problem.

This occurs when anisotropic filtering is used for shadows.

It does not seem to be noticeable if it is up to 2x.

However, there is no advantage to using anisotropic filtering for shadows, so it is preferable not to use it.

**Comment by lwjglgamedev** [comment]
Thanks for reporting! I I will reopen to check if I can add something about this.

**Comment by EnterOgawa** [comment]
Below is a description of a solution to a problem with cascade boundaries when using anisotropic filtering, and I tried it.
(https://learn.microsoft.com/en-us/windows/win32/dxtecharts/cascaded-shadow-maps)

However, it did not work.
Probably due to my own lack of HLSL knowledge...

I hope this helps!

**Comment by lwjglgamedev** [comment]
Just uploaded a fix for this. It should improve the quality. However I will keep on trying to improve it, specially when camera moves.
