### ISSUE TITLE
About shadow quality

### ISSUE THREAD

**Issue by EnterOgawa** [lwjglgamedev/vulkanbook#43]
The following differences exist when the same model is displayed.

The code in this book displays the following
![image](https://user-images.githubusercontent.com/113655398/205482498-2c3df061-f7c5-45e4-a57f-73c871506822.png)

SaschaWillems' sample shows the following display.
https://github.com/SaschaWillems/Vulkan/tree/master/examples/shadowmappingcascade
![image](https://user-images.githubusercontent.com/113655398/205481618-170e2ad9-6ccd-4e82-a0e1-a77563e2747e.png)

This model was downloaded from.
https://vulkan.gpuinfo.org/downloads/vulkan_asset_pack_gltf.zip

The images were arranged as follows.
![image](https://user-images.githubusercontent.com/113655398/205481892-3e29b103-18c4-45e6-a9c1-28472e01f74a.png)

This gltf model contains textures, so I've added minimal changes to make it loadable.

ModelLoader.java
189Line
### 
      ...
      ModelData.Material material = processMaterial(aiMaterial, texturesDir, flags);
      ...

331Line:
###
     private static ModelData.Material processMaterial(AIMaterial aiMaterial, String texturesDir, int flags) {
        try (MemoryStack stack = MemoryStack.stackPush()) {
            AIColor4D colour = AIColor4D.create();

            Vector4f diffuse = ModelData.Material.DEFAULT_COLOR;
            int result = aiGetMaterialColor(aiMaterial, AI_MATKEY_COLOR_DIFFUSE, aiTextureType_NONE, 0,
                    colour);
            if (result == aiReturn_SUCCESS) {
                diffuse = new Vector4f(colour.r(), colour.g(), colour.b(), colour.a());
            }
            AIString aiTexturePath = AIString.calloc(stack);
            aiGetMaterialTexture(aiMaterial, aiTextureType_DIFFUSE, 0, aiTexturePath, (IntBuffer) null,
                    null, null, null, null, null);
            String texturePath = aiTexturePath.dataString();
            if (texturePath != null && texturePath.length() > 0) {
                texturePath = texturesDir + File.separator + new File(texturePath).getName();
				if( texturePath.indexOf("*") != -1) {
					texturePath += "@@" + flags ; 
				}
                diffuse = new Vector4f(0.0f, 0.0f, 0.0f, 0.0f);
            }

            AIString aiNormalMapPath = AIString.calloc(stack);
            Assimp.aiGetMaterialTexture(aiMaterial, aiTextureType_NORMALS, 0, aiNormalMapPath, (IntBuffer) null,
                    null, null, null, null, null);
            String normalMapPath = aiNormalMapPath.dataString();
            if (normalMapPath != null && normalMapPath.length() > 0) {
                normalMapPath = texturesDir + File.separator + new File(normalMapPath).getName();
				if( normalMapPath.indexOf("*") != -1) {
					normalMapPath += "@@" + flags ; 
				}
            }

            AIString aiMetallicRoughnessPath = AIString.calloc(stack);
            Assimp.aiGetMaterialTexture(aiMaterial, AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_METALLICROUGHNESS_TEXTURE, 0, aiMetallicRoughnessPath, (IntBuffer) null,
                    null, null, null, null, null);
            String metallicRoughnessPath = aiMetallicRoughnessPath.dataString();
            if (metallicRoughnessPath != null && metallicRoughnessPath.length() > 0) {
                metallicRoughnessPath = texturesDir + File.separator + new File(metallicRoughnessPath).getName();
				if( metallicRoughnessPath.indexOf("*") != -1) {
					metallicRoughnessPath += "@@" + flags ; 
				}
            }
            ...

Texture.java
###
 	public Texture(Device device, String fileName, int imageFormat) {
		Logger.debug("Creating texture [{}]", fileName);
		recordedTransition = false;
		this.fileName = fileName;
		ByteBuffer buf;
		try (MemoryStack stack = MemoryStack.stackPush()) {
			IntBuffer w = stack.mallocInt(1);
			IntBuffer h = stack.mallocInt(1);
			IntBuffer channels = stack.mallocInt(1);
			int importMark = fileName.indexOf("*") ;
			if( importMark != -1) {
				String[] split = fileName.substring( importMark + 1, fileName.length()).split("@@") ;
				int	textureIndex = Integer.parseInt( split[0]) ;
				int	flags = Integer.parseInt( split[1]) ;
				fileName = new File( fileName).getParentFile().listFiles()[0].getAbsolutePath().replace( "" + File.separatorChar + "", "/") ;
				AIScene		aiScene = null ;
				try {
					aiScene = aiImportFile( fileName, flags) ;
					if( aiScene == null) {
						throw new RuntimeException("Error loading model [modelPath: " + fileName + "]");
					}
					PointerBuffer	mTextures = aiScene.mTextures() ;
					AITexture		aiTexture = AITexture.create( mTextures.get( textureIndex)) ;
					buf = stbi_load_from_memory( aiTexture.pcDataCompressed(), w, h, channels, 4) ;
					if( buf == null) {
						throw new RuntimeException("Image file [" + fileName + "] not loaded: " + stbi_failure_reason());
					}
				} finally {
					if( aiScene != null) {
						aiReleaseImport( aiScene) ;
					}
				}
			}
			else {
				buf = stbi_load( fileName, w, h, channels, 4) ;
				if( buf == null) {
					throw new RuntimeException("Image file [" + fileName + "] not loaded: " + stbi_failure_reason());
				}
			}
			setHasTransparencies(buf);
			width = w.get();
			height = h.get();
			mipLevels = (int) Math.floor(log2(Math.min(width, height))) + 1;

			createTextureResources(device, buf, imageFormat);
		}

		stbi_image_free(buf);
	}

**Comment by lwjglgamedev** [comment]
My guess is that this is because in the shadow map I do not add support for transparencies. Leafs may be just tetxures inside quads, which produce this lack of resilution. To fix that you should add a fragment shader to shadow render and pass material information. I will review this and probably add support for that in the future.

**Comment by EnterOgawa** [comment]
Sorry for the delay in contacting you.

In order to investigate the cause of this, I tried to create a shadow with forward rendering, in which case it appears correctly.

So, I stopped destroying fragments in the fragment shader when creating with forward rendering, and I got the same shadows as created with the geometry shaders.

I feel that this is because the geometry shader cannot discard fragments.

Here is the fragment shader when the shadows are created by forward rendering.

```
#version 450

layout (constant_id = 0) const int SHADOW_MAP_CASCADE_COUNT = 4 ;
layout (constant_id = 1) const int MAX_TEXTURES = 100 ;

layout(location = 0) in vec2 inTextCoords;
layout(location = 1) flat in uint inMatIdx;

struct Material {
    vec4 diffuseColor;
    int textureIdx;
    int normalMapIdx;
    int metalRoughMapIdx;
    float roughnessFactor;
    float metallicFactor;
};

layout (std430, set=1, binding=0) readonly buffer srcBuf {
    Material data[];
} materialsBuf;
layout(set = 2, binding = 0) uniform sampler2D textSampler[MAX_TEXTURES];

void main() 
{    
    Material material = materialsBuf.data[inMatIdx] ;

    float alpha = texture( textSampler[ material.textureIdx], inTextCoords).a;
    if (alpha < 0.5) {
        discard;
    }
}
```

If we do the following, the shadows will be the same as those created by the geometry shader.

```
    ...
    float alpha = texture( textSampler[ material.textureIdx], inTextCoords).a;
//    if (alpha < 0.5) {
//        discard;
//    }
```

**Comment by lwjglgamedev** [comment]
I'ts been a long time, but I'm currently working on adding support for transparencies in shadows. The approach is what I mentioned, passing texture information while generating depth maps and discard fragments which are below a certain alpha threshold.
