### ISSUE TITLE
There are many places where `model*` is written as `mesh*`

### ISSUE THREAD

**Issue by rongcuid** [lwjglgamedev/vulkanbook#45]
I think this might be when the code updates but the book does not keep up? There are quite a lot of examples in Chapter 5-7. Might be more in future chapters which I haven't gone through yet.

**Comment by lwjglgamedev** [comment]
Can you be a litle bit more specific pointing to a section? The book should eb updated with  the code, may  maybe I miss soomething when updating. Thanks in advance.

**Comment by rongcuid** [comment]
Say Chapter 7, meshId -> modelId

**Comment by lwjglgamedev** [comment]
Ok, I will have a look.

**Comment by lwjglgamedev** [comment]
I've already uploaded a fix. If you see any other inconsistencies, please reopen.

Thanks for reporting.
