### ISSUE TITLE
Poll about build System

### ISSUE THREAD

**Issue by lwjglgamedev** [lwjglgamedev/vulkanbook#5]
I'd like to know your opinion about the build system that should be used for this. Would you like to change it to Gradle (Kotlin DSL) or stick with Maven?

Please leave your thoughts (rationale for your preferred option is appreciated)

**Comment by SWinxy** [comment]
IMO It's all based on preference. I use maven for my work, and thus I don't know much about Gradle.

**Comment by lwjglgamedev** [comment]
Thanks for commenting. Gradle is less verbose than maven and can speed up build times (mainly due to an ever runnig daemon). However, my background comes also from maven. Although gradle is much more concise, I've found in the past difficult to achive cretain thins that are trivial and maven.

**Comment by lwjglgamedev** [comment]
I've just uploaded gradle scripts. By now I will keep both maven and gradle.
