### ISSUE TITLE
Update descriptor sets between frames

### ISSUE THREAD

**Issue by tlf30** [lwjglgamedev/vulkanbook#54]
Hello,
I believe the way descriptor sets are implemented does not allow them to be updated between frames. The vulkan specification specifies that a descriptor set (and associated resources) cannot be updated while in use by a command buffer. Currently this book only creates a single descriptor set for each binding, and does not allow for the descriptor sets to be updated since they are always in use be frames in flight. (currently any updates that happen and work are just timing coincidence)

A couple approaches to fix:
1. Wait for all command buffers to complete before updating descriptor sets. This has the major disadvantage that you no longer have multiple frames in flight if you have descriptors that need updated every frame (or very often)
2. Create a descriptor set per frame in flight, then update only that descriptor set with the new value. On the next frames, you will need to update those descriptor sets as well until all frames are updated. (Lots of logic)
3. Dynamically create a new descriptor set for each update, and each update gets its own buffers/samplers. The previous descriptor set and associated bound resources (buffers/samplers) get added to an unload queue and unloaded once no longer in use. (This is the approach I took on my engine, it requires a lot of logic, and has pros/cons to option 2. The largest con is that depending on the implementation if releasing the descriptor sets back to the pool, then when a new descriptor set is allocated it can take a while to allocate depending on the GPU and driver. The best approached to this is to have a local cache of already allocated descriptor sets to use for updates. In my engine I do not currently do this and I release back to the pool, but in the future I will be implementing my own local cache. This seems to make the largest difference in mobile vulkan implementations.)

Just something to think about. It could be great to have this fixed as most vulkan tutorials do not address this issue, and this is probably a blocking item for getting texture support implemented for ImGui. In my ImGui implementations I use a texture sampler array, and update it based on which textures need to be used by imgui.

Example shaders:
Frag:
 ```glsl
#version 460
#injdef

#ifndef MAX_UI_TEXTURE_COUNT
#define MAX_UI_TEXTURE_COUNT 64
#endif

layout (location = 0) in vec2 inTextCoords;
layout (location = 1) in vec4 inColor;
layout (location = 2) flat in int inTextId;

layout(binding = 0) uniform sampler2D textureSamplers[MAX_UI_TEXTURE_COUNT];

layout (location = 0) out vec4 outColor;

void main()
{
    outColor = inColor  * texture(textureSamplers[inTextId], inTextCoords);
}
```

Vert:
```glsl
#version 460
#injdef

layout (location=POSITION) in vec2 position;
layout (location=TEX_COORD0) in vec2 texCoord0;
layout (location=COLOR) in vec4 color;

#alias scale push_constants.scale
//#alias translate push_constants.translate //not currently used...
#alias textureId push_constants.textureId
layout (push_constant) uniform PushConstants {
    vec2 scale;
    //vec2 translate; //Not currently used...
    int textureId;
} push_constants;

layout (location = 0) out vec2 outTextCoords;
layout (location = 1) out vec4 outColor;
layout (location = 2) out int outTextId;

out gl_PerVertex
{
    vec4 gl_Position;
};

void main()
{
    outTextCoords = texCoord0;
    outColor = color;
    outTextId = push_constants.textureId;
    gl_Position = vec4(position * push_constants.scale + vec2(-1.0, 1.0), 0.0, 1.0);
    //gl_Position = vec4(position * push_constants.scale + push_constants.translate, 0.0, 1.0);
}
```

Thanks,
Trevor

**Comment by lwjglgamedev** [comment]
I'm just trying to understand what you propose. Currently, in the book, it is shown precisely that you cannot change descriptor sets when in fly. This is shown for example with view matrices, following the number 2 approach you suggest. In that case there is a buffer and associated descriptor set per swap chain image.

The approach number 3 may be a potential solution for more complex cases, but I think the ideas you emntion are explained. Am I missing something?

**Comment by tlf30** [comment]
Sorry, I must have missed that last time I went back through the book. I'll review and get back to you.

**Comment by lwjglgamedev** [comment]
Closing this. Please reopen if you still think there is something missing

**Comment by tlf30** [comment]
Hello @lwjglgamedev sorry for the delay on this, I have been doing a lot of traveling. I think everything is there and all good.
