### ISSUE TITLE
Severity verbose bit and disposing vkInstance.

### ISSUE THREAD

**Issue by NullsByteBack** [lwjglgamedev/vulkanbook#61]
**Describe the bug**
Including VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT in the instance MESSAGE_SEVERITY_BITMASK member
causes a null pointer exception when exiting application.

**To Reproduce**
1. Chapter: Any
2. Go to: Instance.java.
3. Include VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT in the MESSAGE_SEVERITY_BITMASK member.
4. Run and close the application.
5. See error

**Expected behavior**
Application closes successfully.

**Screenshots**
None

**Please complete the following information):**
- OS: Linux amd64 (Fedora 38)
- Java version: 20.0.1+9
- Lwjgl version:  3.3.2

**Additional context**
Removing debugUtils.pfnUserCallback().free(); from Instance.cleanup() seem to stop the error,
however the callback then leaks.

**Comment by lwjglgamedev** [comment]
Just inverted the order of freeing the callback. Thanks for reporting!
