### ISSUE TITLE
chapter 02 - turning on validation layers for macos

### ISSUE THREAD

**Issue by RefuX** [lwjglgamedev/vulkanbook#65]
If you could please enhance your note to turn on Validation Layers that when developing on MacOS you need to use the Vulkan Loader library and not the MoltenVK library, which you do by adding these VM options:
```-Dorg.lwjgl.librarypath=/usr/local/lib -Dorg.lwjgl.vulkan.libname=libvulkan.1.dylib```

Relevant documentation:
https://vulkan.lunarg.com/doc/sdk/1.3.261.1/mac/getting_started.html

```For desktop applications, the recommended usage model is to use the MoltenVK dynamic library in conjunction with the Vulkan Loader. In this scenario the MoltenVK library takes on the role of the ICD from the point of view of the application and the Vulkan Loader. In this mode, you link only to the Vulkan Loader, and not the MoltenVK library directly. You will include the MoltenVK and the Vulkan Loader dynamic libraries in your application's bundle when distributing your software. When the Vulkan SDK is installed on macOS, these runtime components are placed in system directories and can be easily used during development without embedding them in the app bundle. Even if you decide to ship your application linked to the static MoltenVK library, during development we recommend you make use of the Vulkan Loader and Vulkan Validation Layers as they are a tremendous boon for debugging your Vulkan-based rendering code.```

**Comment by lwjglgamedev** [comment]
Done. Thanks again for reporting this!
