### ISSUE TITLE
Use of VkDrawIndexedIndirectCommand Struct is not necessary.

### ISSUE THREAD

**Issue by Mjrlun** [lwjglgamedev/vulkanbook#72]
In Chapter 16, the struct `VkDrawIndexedIndirectCommand` is used to input into the `indirectBuffer`, as well as its animation equivalent. However, due to the fact that the struct is placed into its buffer *without padding*, there is no need to allocate these structures (saving memory while uploading).

Rather than 
``` java
for (VulkanModel.VulkanMesh vulkanMesh : vulkanModel.getVulkanMeshList()) {
                    VkDrawIndexedIndirectCommand indexedIndirectCommand = VkDrawIndexedIndirectCommand.calloc(stack);
                    indexedIndirectCommand.indexCount(vulkanMesh.numIndices());
                    indexedIndirectCommand.firstIndex(vulkanMesh.indicesOffset() / GraphConstants.INT_LENGTH);
                    indexedIndirectCommand.instanceCount(entities.size());
                    indexedIndirectCommand.vertexOffset(vulkanMesh.verticesOffset() / VertexBufferStructure.SIZE_IN_BYTES);
                    indexedIndirectCommand.firstInstance(firstInstance);
                    indexedIndirectCommandList.add(indexedIndirectCommand);
                    ...
```

You can instead do
``` java
int i = 0;
for (VulkanModel.VulkanMesh vulkanMesh : vulkanModel.getVulkanMeshList()) {
                    dataBuffer
                              .putInt(i, vulkanMesh.numIndices())
                              .putInt(i += 4, entities.size())
                              .putInt(i += 4, vulkanMesh.indicesOffset() / GraphConstants.INT_LENGTH)
                              .putInt(i += 4, vulkanMesh.verticesOffset() / VertexBufferStructure.SIZE_IN_BYTES)
                              .putInt(i += 4, firstInstance)
                    i += 4;
                    ...
```
*Note: You will need to move the allocation of the command byte buffer above the for loop (with proper checks of course). Also, the order I gave is the precise order of the Struct's fields, but keep in mind to check the order of inserts if things break.*

**Comment by lwjglgamedev** [comment]
Althouh I totally agree that your approach is mor efficient (when dealing with multiple different models) I think it would reduce "readibility" and "undestability". Therefore, I'd preffer to stick with current code. Maybe an intermediate approach would be to mention your apporach as a way to optimize memory consumption (only when loading models).
