### ISSUE TITLE
`firstInstance` field is not used, but is defined

### ISSUE THREAD

**Issue by Mjrlun** [lwjglgamedev/vulkanbook#73]
In Chapter 16, when defining the `VkDrawIndexedIndirectCommand` structs for both static and animated meshes, the `firstInstance` field is defined, but not used in the shaders.

To fix this issue, simply define the field as `0` when defining the struct.

**Comment by lwjglgamedev** [comment]
This is required for material Index. You can comment that part and see it will fail, for example, for animated meshes.

**Comment by lwjglgamedev** [comment]
Ok, you will not find it in the shader code but it is used behind the curtains. To simplify, let's focus on static models. You will have big buffer which contains all the meshes vertices. Where you should start reading for a sepcific mesh is controlled by the `vertexOffset` attribute (which you wil not see either in the sahder code). The associaed indices are controlled by the `firstIndex` parameter. But we are rendering, all the entities associated to a specific mesh from a model using a single indirect draw command. This means, that we need to use a buffer which contains per instance (or per entity) data, such as model matrix, material index and so on. This is what is controlled by `firstInstance` attribute. You can think of it like a pointer to the big buffer which holds that "per entity" data. That structure is loaded in the `loadInstanceData` and contains a model matrix and a material index. That structure is populated following a sepecifc order so when drawing, the `firstIntance` field will act as a pointer to the data of the parts entity (instance) associated to the mesh being rendered (and will be incremented under the hood for the rest of entities drawn in the single command). 

Just realized this is not explained very well in the book. If you are ok with this explanation I will use this isse to update it.

**Comment by Mjrlun** [comment]
Makes sense to me
