### ISSUE TITLE
Too many texture descriptors created in Chapter 16

### ISSUE THREAD

**Issue by Mjrlun** [lwjglgamedev/vulkanbook#74]
In Chapter 16, the class `GeometryRenderActivity`'s `createDescriptorPool` method creates a descriptor pool with the number of image descriptors equal to `engineProps.getMaxMaterials() * 3`, rather than 1, which is what would be expected with a texture array.

**Comment by lwjglgamedev** [comment]
I think this is not right. You need to create one descriptor set per texture even if they are in an array. They are accessed through an array of sampler2D elements not by a sampler2DArray. In the later case that would be correct. Do you agree?

**Comment by Mjrlun** [comment]
I took a moment to confirm it, I apologize; you are correct: each texture is considered its own descriptor.
