### ISSUE TITLE
Line moved to `GeometryRenderActivity.render` still exists in Chapter 16's readme

### ISSUE THREAD

**Issue by Mjrlun** [lwjglgamedev/vulkanbook#75]
![image](https://github.com/lwjglgamedev/vulkanbook/assets/84252662/02bfb475-06ca-4829-b5ff-57d60bb51f1f)

The bottommost line does not exist in the actual codebase, but exists in the readme.

**Comment by lwjglgamedev** [comment]
Thanks!
