### ISSUE TITLE
(MAJOR BUG) Specialization Constants cannot be used to size arrays.

### ISSUE THREAD

**Issue by Mjrlun** [lwjglgamedev/vulkanbook#76]
According to people in the Vulkan Discord, Specialization Constants cannot be used to size arrays within the layout of the shader. This is due to a compile-time issue which has been identified by users, but not been fixed by the Vulkan, GLSL, and SPIR-V developers, which means that the default value of the spec-constant will become static for those arrays.

This means either of two solutions are necessary, of which some can be remedied easily.

The first solution entails replacing *all* arrays sized using spec constants with storage buffers, rather than uniforms. This obviously will not work for texture sampler arrays, but for other structs will work fine. Ones that will work with this are the `Lights[]` and `CascadeShadows[]` arrays within the `lighing_fragment` shader. The syntax ramifications of this are that `MAX_LIGHTS` as a spec constant is no longer necessary, and the ambient light vector and light count will need to be moved into the `ProjUniform` uniform. The other problem needing to be solved with this is uploading to a storage buffer every single frame (for the shadows and lights). 

I'd recommend making the cascade shadows storage buffer shared across to the `shadow_geometry` shader, although that means that it will need to be calculated in that section instead.

Look into Host Visible with Device Local memory types for storage buffers, which will allow you to upload to the buffer in the same way as a uniform would.

The second solution requires the use of either `shaderc_compile_options_add_macro_definition` or using `String.replace` to replace constants in the shader created using `#define`. This would work well for changing the number of allowed textures in the texture sampler (`geometry_fragment` and `shadow_fragment`), as well as setting the number of shadow cascades on-the-fly (`shadow_geometry`).

I hope this is helpful solving this issue, and Godspeed.

**Comment by lwjglgamedev** [comment]
Hi, I was thinking on using GL_EXT_nonuniform_qualifier extension which allows not to set a fixed size for arrays. What do you think of this approach?

**Comment by Mjrlun** [comment]
I think that could be a good solution, although I will note, at least in my engine, texture array size is fixed.
This is partially because in order to expand it would require reloading all of the textures, which is to my knowledge impossible.
As such, I instead used the shaderc stuff for the array-sized spec constants.
I am open to it, so if you think that solution could be used more cleanly and effectively, I'd be happy to see it.

**Comment by Mjrlun** [comment]
The only issue I noticed is that `lightBuffers` is created using `VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT` when it should be using `VK_BUFFER_USAGE_STORAGE_BUFFER_BIT`. If there are any other issues, they will have been validation errors you could check with the debug utils extension.

**Comment by lwjglgamedev** [comment]
Good catch. No validations errors from my side. I wiill proceed with the rest of chapters. Regarding spec constants, I think it is good to introduce this concept, the only thing is that it will need to be done in next chapter (13).

**Comment by lwjglgamedev** [comment]
The only pending changes now are related to the array of samplers.

**Comment by lwjglgamedev** [comment]
I've updated the text to explain how macros can be used with sahderc but prefered to keep the code as it is. I want to add new chapters about ray tracing and need to focus on that.
