### ISSUE TITLE
FontManager is in the second Appendix but is not in any of the book chapters.

### ISSUE THREAD

**Issue by Mjrlun** [lwjglgamedev/vulkanbook#78]
As the title states. I recommend adding it in the GUI chapter considering that's what it's used for.

**Comment by lwjglgamedev** [comment]
It is appendix 2 because it is there when it is first used. In the GUI chapter I just want to focus on the integration of ImGui into Vulkan render, just that. In appendix 2, ImGui usage is shown creating menus, and using fonts.
