### ISSUE TITLE
Chapter 9, Parameter difference between guide and source.

### ISSUE THREAD

**Issue by Wertuu** [lwjglgamedev/vulkanbook#79]
In C9, aside from there not being a block in the guide for the static final VEC4_SIZE, there is also a spot under the 'Completing the Changes' section, in its second block, where the textureSampler initializer is. In that spot, the guide says the creation parameters taken are a Device and an Int, but the source says that it also takes a boolean.

**Comment by lwjglgamedev** [comment]
Thanks!
