### ISSUE TITLE
Source, Guide mismatch on Chapter 11

### ISSUE THREAD

**Issue by Wertuu** [lwjglgamedev/vulkanbook#81]
The very last block on Chapter 11 in the guide, wherein you change the Main.java class, the guide says that the input method is called 'handleInput' and it isn't overridden, but the source has it as the overridden inherited 'input'. Not a big issue, but it caused me to wonder if I was crazy for a moment.

**Comment by lwjglgamedev** [comment]
Thanks for reporting!
