### ISSUE TITLE
Chapter14, Multiple spots that the guide is missing information.

### ISSUE THREAD

**Issue by Wertuu** [lwjglgamedev/vulkanbook#82]
Howdy, me again.

So in the ModelLoader class, it uses a 'findAIAnimNode' method, but the guide didn't include it. 
I'm fairly certain the guide didn't include the Bone or VertexWeight records either in that class, but it's possible I missed it.

In the Main class, it sets a maxFrames variable that wasn't created in the guide.

In the AnimationComputeActivity class, in the recordCommandBuffer method, the guide says that the line is supposed to use the DescriptorSets.numVertices variable, but in the source, it uses the groupSize.
I also didn't see the record for the EntityAnimationBuffer in the guide, but it's possible I missed it.

This guide has been super helpful in converting to Vulkan, and I thank you deeply for your time.

**Comment by lwjglgamedev** [comment]
Thanks for reporting ! I thinkeverything should be closed by now. If you do find that something is still missing please reopen.
