### ISSUE TITLE
Chapter 15, guide missing instructions.

### ISSUE THREAD

**Issue by Wertuu** [lwjglgamedev/vulkanbook#84]
Hello, in Chapter 15, in the final block of the guide, you state that we'll be defining two implementations of the IGuiInstance interface, SimpleGui() and DemoGui(), but both are only in the source.

Also, minorly, the input section in the same block is still named "handleInput" whereas in the guide it is simply "input".

Thank you deeply for your time in creating this, it is the only one of its kind.

**Comment by lwjglgamedev** [comment]
Thanks for reporting the issue!
