### ISSUE TITLE
i have same problem in `vscode`. It dosen't want to load relative paths of shaders.

### ISSUE THREAD

**Issue by aftamat4ik** [lwjglgamedev/vulkanbook#85]
i have same problem in `vscode`. It dosen't want to load relative paths of shaders.

```
Exception in thread "main" java.lang.RuntimeException: java.nio.file.NoSuchFileException: resources\shaders\fwd_vertex.glsl
        at org.vulkanb.eng.graph.vk.ShaderCompiler.compileShaderIfChanged(ShaderCompiler.java:71)
        at org.vulkanb.eng.graph.ForwardRenderActivity.<init>(ForwardRenderActivity.java:63)
        at org.vulkanb.eng.graph.Render.<init>(Render.java:39)
        at org.vulkanb.eng.Engine.<init>(Engine.java:18)
        at org.vulkanb.Main.main(Main.java:22)
Caused by: java.nio.file.NoSuchFileException: resources\shaders\fwd_vertex.glsl
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
        at java.base/java.nio.file.Files.readAllBytes(Files.java:3288)
        at org.vulkanb.eng.graph.vk.ShaderCompiler.compileShaderIfChanged(ShaderCompiler.java:57)
        ... 4 more
```
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/f92917bd-9f53-4612-b11c-dd71c441e773)
I know there is a way to fix it, but i'm only learning java and my knowlege is not enough. Yet i tried to fix function `compileShaderIfChanged` by advices from Stackoverflow, with no luck.
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/065c765f-bdf3-4383-83b9-7c2123afe412)
problem comes from this line:
```java
Files.write(spvFile.toPath(), compiledShader);
```
When i try to manually run the Jar it fails with this error:
```java
> cd .\booksamples\chapter-09\target\
> \booksamples\chapter-09\target> java -jar chapter-09-1.0.0.jar

> Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/vulkanb/Main has been compiled by a more recent version of the 
Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:621)
```
vscode don't want to work with Java workspaces and therefore relative paths to shaders / assets don't work in it. Maybe there is short fix that can be used in code to convert relative path to absolute path? This bug probably will disappear if i install `idea` but problem will exist anyway for all other users of vscode.

_Originally posted by @aftamat4ik in https://github.com/lwjglgamedev/vulkanbook/issues/7#issuecomment-2000543214_

**Comment by lwjglgamedev** [comment]
Sorry I responded in the comment you mention. Please provide the info that I repuesto in that commment. I will have a look and provide some updates.

**Comment by aftamat4ik** [comment]
Thanks for response. 
I'm on Windows, my JDK's(8,11,17,21) taken from https://adoptium.net/
This is `VSCode` settings, used to load `JDK's`:
```json
{
    "java.configuration.runtimes": [
        {
            "name": "JavaSE-21",
            "path": "***\\Java\\jdk-21",
            "default": false
        }
        ,{
            "name": "JavaSE-17",
            "path": "***\\Java\\jdk-17",
            "default": true
        }
        ,{
            "name": "JavaSE-11",
            "path": "***\\Java\\jdk-11",
            "default": false
        }
        ,{
            "name": "JavaSE-1.8",
            "path": "***\\Java\\jdk-8",
            "default": false
        }
    ],
    "java.import.gradle.java.home": "C:\\Program Files\\Java\\jdk-17",
    "java.jdt.ls.java.home": "c:\\Program Files\\Java\\jdk-17"
}
```
I also have set `JAVA_HOME` inside `Windows` environment and all works fine.
This is `VSCode` current extensions, they all came from "Extension Pack for Java".
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/550c8c19-7573-4c65-ab3e-714bb4125706)

I used `git clone` to copy book project at local drive. Then i imported book folder inside `VSCode` in usual way.
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/8a4f38c8-c408-4ced-b72a-0cee0f6f535a)
After opening project it shows popup to select whether i want to use Gradle or Maven. I'm not ... that much underestand yet, how they work, but, i guess need to select Maven here.
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/9c0e1ab0-2a09-4e44-b50f-2f68eec72d30)
Then Java starts to build and compile ... something. I just wait.
After compilation is done i created workspace using `File->Save Workspace As`, just in case.
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/12284563-cd76-4d74-8e6a-a1c8cd7ad5c5)
Workspace generated at the root of the book folder.
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/d04e7dbf-688c-432e-8313-014f3d5e7ce2)
I also had to change `<imgui-java.version>` from `<imgui-java.version>1.86.11</imgui-java.version>` to `<imgui-java.version>1.8</imgui-java.version>` because it won't build without this change.
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/aa59dc27-fe86-4551-9265-6953267448fe)

Now i do usual maven stuff like "mvn install", "mvn package" in the terminal.
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/cbe3f0a0-6bf3-438f-9edc-cfad33e3df29)
it also shows errors for chapter 15, don't know what's in there
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/ea230156-dfa4-4136-b6f1-b3bcc4498205)

![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/8623ccb7-84e1-41c1-b9bc-ed790b99a073)

now need to restart VScode to reload workspace.
And it will load this project into "Maven" and "Java Projects" tabs.
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/1d777bba-f611-414a-9705-e2cc3685fe22)
Usually this tabs appear at the bottom of left sidebar.
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/89d37032-4566-4843-a9b9-6ace884b5934)
but you can open right sidebar by clicking to here:
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/4ebb619d-6b08-4c3b-bd5e-912f37e588e3)
And then just drag "Maven" and "Java Projects" tabs into right sidebar.
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/c21105b3-1865-4669-b91d-d674c2b99b28)
From "Maven" tab we can execute maven tasks for each of the "sub-projects" by going to "lifecycle" popup.
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/4542c659-8325-4a66-af91-3f88edff82b3)
Do "install" for chapter 9.
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/a67de2c3-07e1-4a91-abd9-e70cbe8c4856)
It succeed.
Now try to run it.
To do so, go to "Java Projects" tab and search there for "chapter-9". There will be "run and debug" button.
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/fc9f2c88-5280-4bc4-8c4a-ef299a040cd5)
Using this button we can easily launch, for example, "chapter-2".
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/508d464e-9944-4873-8b75-a9f3a2adbdf7)
But it won't work with "chapter-9" nd will show errors, that i provided above.
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/2421d043-15b5-4cf0-9a8d-c8afb67fa508)

**Comment by lwjglgamedev** [comment]
Ok, great information.

I've just installed the same extensions as you, on Windows, and I'm able to execute the examples without any problem. So, obvioulsy, your environment is using a different working directory. Can you try to add this line:

```System.out.println("############ ABSOLUTE PATH: [" + glslFile.getAbsolutePath() + "]");```

In ShadercCompiler class, after the line that instantiates the `File` instance?:

```File glslFile = new File(glsShaderFile);```

This should be line 53 if you have not modifuied that class.

The first difference that I see is that I'm using OpenJDK binaries, instead of adoptium. I don't know if this changes working directory,

**Comment by aftamat4ik** [comment]
i did as you said
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/192186c1-c6c1-4320-b6bb-729f46afa74c)
here's output:
```sh
> ############ ABSOLUTE PATH: [H:\Dev\Java\Git\lwjgl-vulkan-book\resources\shaders\fwd_vertex.glsl]
```
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/b020d796-af72-424c-b690-f0730d311715)

I underestand it now. it thinks current project as root, not individual one. But what to do?

**Comment by lwjglgamedev** [comment]
Just open the individual folder of each sample, not the root folder. It is
explained for intellij i will probably add some yext for vscode users

**Comment by aftamat4ik** [comment]
yes, i just opened `chapter-9` as individual project and it worked.
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/18ba0387-8cdb-4922-a40b-fab20ca704e9)

![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/29abd2e7-1774-4716-81bb-280ef542e7c9)
i doubt why it dosen't detect sub-projects as `user.dir` individually... i't probably related to `vscode` itself or to the `Maven` or even to `jdk`, don't know.
Marking it as fixed. If anyone? reading this, has better solution - let us know in this thread, please.
