### ISSUE TITLE
Fence not being reset

### ISSUE THREAD

**Issue by ViniciusCoral** [lwjglgamedev/vulkanbook#86]
**Describe the bug**

On chapter 6 (bookContents), at the very end of 'Using Pipeline' session you mention:

> Finally, we need to slightly modify the submit method in the ForwardRenderActivity, we need to remove the waiting form the fence that protects access to the command buffer since this is done now in the recordCommandBuffer method.

But then in your example you remove the fence reset,

`public class ForwardRenderActivity {

    public void submit(Queue queue) {
        try (MemoryStack stack = MemoryStack.stackPush()) {
            int idx = swapChain.getCurrentFrame();
            CommandBuffer commandBuffer = commandBuffers[idx];
            Fence currentFence = fences[idx];
            SwapChain.SyncSemaphores syncSemaphores = swapChain.getSyncSemaphoresList()[idx];
            queue.submit(stack.pointers(commandBuffer.getVkCommandBuffer()),
                    stack.longs(syncSemaphores.imgAcquisitionSemaphore().getVkSemaphore()),
                    stack.ints(VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT),
                    stack.longs(syncSemaphores.renderCompleteSemaphore().getVkSemaphore()), currentFence);
        }
    }
    ...
}`

Making the program crash due to the fence not being reset.

Apparently there is no necessary change to this method in this chapter.

**To Reproduce**

1. Chapter 6
2. Go to ForwardRenderActivity.submit(queue)
3. remove the fence reset(like described in the chapter)
4. execute the application
5. See error

**Expected behavior**
The application should not crash

**Screenshots**

**Please complete the following information):**
 - OS: Windows 10
 - Java version Temurim 17

**Additional context**

**Comment by lwjglgamedev** [comment]
Thanks for reporting! The source code was ok but the chapter text was not in sync
