### ISSUE TITLE
Doubt on chapter 8 processMaterial method

### ISSUE THREAD

**Issue by Bernasss12** [lwjglgamedev/vulkanbook#88]
As I was trying to follow, and comprehend the 8th chapter of the book, when the processMaterial method is described I don't fully understand what we are doing here. The description of the method seems to be describing the opposite of what the method actually does:

It states that we get the texture path and then retrieve the color associated to that material but in the code it seems that the color is retrieved prior to the texture path and then overwritten with white if the texture path is not null or empty:

https://github.com/lwjglgamedev/vulkanbook/blob/7909589202a110b679067775a83b756a86fc2401/bookcontents/chapter-08/chapter-08.md#L110-L139

The description as seen in line 139 for easier reading:

>  We get the the texture associated to the diffuse color of the material by calling the `aiGetMaterialTexture` function. This function receives as a parameter an instance of an `AIString` that will be used to return the texture path. If the path is present (if it is not null or empty) we insert the path where the textures for this model will reside. Many models use absolute paths, which probably won't fit with the path were you store the model. This is the reason why get just the file name, without the possible path (either absolute or relative)that could be used in the model. Once we have got the texture path, we retrieve the material diffuse color by calling the `aiGetMaterialColor` function. All that information is stored in an instance of the `ModelData.Material` class. The constructed instance is appended to the list passed as a parameter that will contain all the materials of the model. The `ModelData` needs to be modified to include the definition of the `ModelData.Material` class and to hold the data for the associated materials: 

Is this a mistake?

**Comment by lwjglgamedev** [comment]
Thanks for reporting! It was a a mistake, my mistake. Probably code started originally as the text and then changed my mind, the code, but not the text.
