### ISSUE TITLE
Explain `MouseInput.displVec`

### ISSUE THREAD

**Issue by Laxystem** [lwjglgamedev/vulkanbook#91]
**Is your feature request related to a problem? Please describe.**
I don't understand what it's meant for, what its name means, or why is it calculated like that (why ignore a change of 0?)

**Describe the solution you'd like**
Explain what it is.

**Comment by lwjglgamedev** [comment]
Thanks for reporting, added some explanation and modified the condition to be more correct.

**Comment by Laxystem** [comment]
This is better; But still, why the `rotateX: Boolean` thing? Why ignore a change of 0? Is this a mouse-lagging-behind-FPS thing?

P.s. might be wise to rename it to `mousePositionDelta`.

**Comment by lwjglgamedev** [comment]
You are right, maybe it was old code that triggered an event, but it makes no sense now. I've simplifgied the code. regarding the naming suggestion I think it would be better `deltaPos`. In any case, I will update that in the new version of the book that I'm prepairing.
