### ISSUE TITLE
how to compile to epub or static site?

### ISSUE THREAD

**Issue by travisfw** [lwjglgamedev/vulkanbook#94]
This is folders of text files, which is not ideal for navigation 

Requesting an epub I can read offline, or at least a web page without the GitHub distractions.

I imagine I am not the first to think about this, so I'll refrain from suggesting anything more specific until I know your context.

**Comment by lwjglgamedev** [comment]
What you propose sounds good. Ideally I would like to hots it in gitbook platform, but unfortunatley, I can only host one book for free. Therefore, the alternative would be to generate, automatically, epub / PDF documents processing markdown files. Idealy, this should be integrated in Github CI. Anyone is familiar with the best tool for that? (to save research time)

If you have any other idea, please feel free to comment.

**Comment by lwjglgamedev** [comment]
Just added automatic EPUB generation using pandoc in Github actions. If you detect and issue please report.
